services:
  apa_backend:
    build:
      context: .
      target: backend        # ðŸ‘ˆ construye solo la etapa Python
    container_name: apa_backend
    restart: always
    env_file:
      - .env
    command: ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8080"]
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - FRONTEND_URL=http://192.168.0.11:8080  # âœ… URL base para generar links
      - DJANGO_ALLOWED_HOSTS=192.168.0.11,localhost,apa_backend  # âœ… Hosts permitidos
    volumes:
      - ./backend:/app/backend
      - ./static:/app/static
    expose:
      - "8080"
    networks:
      - sistemas_network

  nginx_apa:
    build:
      context: .
      target: final          # ðŸ‘ˆ usa la etapa Nginx final
    container_name: nginx_apa
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - apa_backend
    networks:
      - sistemas_network

networks:
  sistemas_network:
    external: true